// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFm2jKv3k-RsiBlGldkiWhbmOXp3OKnkE',
    appId: '1:828564717583:web:d28645486aea328b11e37a',
    messagingSenderId: '828564717583',
    projectId: 'logindatabase-a4582',
    authDomain: 'logindatabase-a4582.firebaseapp.com',
    storageBucket: 'logindatabase-a4582.appspot.com',
    measurementId: 'G-5ZFF3P7WDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUoLVB4I5NMn2CE8EVG-9sIi38IvH9Hp0',
    appId: '1:828564717583:android:f57873914ea7b7de11e37a',
    messagingSenderId: '828564717583',
    projectId: 'logindatabase-a4582',
    storageBucket: 'logindatabase-a4582.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xHI-GpTyeg7HgOKRcXkiFSAw1WbqDMY',
    appId: '1:828564717583:ios:7c403c79e74b889211e37a',
    messagingSenderId: '828564717583',
    projectId: 'logindatabase-a4582',
    storageBucket: 'logindatabase-a4582.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1xHI-GpTyeg7HgOKRcXkiFSAw1WbqDMY',
    appId: '1:828564717583:ios:abfabd027e1feee011e37a',
    messagingSenderId: '828564717583',
    projectId: 'logindatabase-a4582',
    storageBucket: 'logindatabase-a4582.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
